# Generated by Django 3.0.7 on 2021-06-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('S_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
